=head1 NAME

muttdelay - A bash script to delay mails written via mutt

=head1 WTF?

This is for scheduling the sending of mails for a specific future time. Unlinke postponing a mail which does not involve the scheduling.

=head2 How it works

=head3 Configuring Vim

Do the following:

    cp /usr/share/muttdelay/muttdelay.vim ~/.vim/plugin/
    echo 'map ,L :call MuttDelay()<CR>' >> ~/.vimrc

=head3 Configuring Cron

And create an hourly cronjob such as:

    0 * * * * /usr/bin/muttdelay cron

=head3 Configuring Mutt

Configure mutt your way and  ensure that you can send mails like this:

    mutt -s subject example@example.com <<< hallo

If it works, you can go on. 

=head3 Use it

Open mutt, compose an email. Use Vim as your editor. After finishing writing your mail don't close Vim, but run

    ,L

and the mail gets scheduled for sending for a later time. You can now leave vim without sending the mail via mutt directly.

The mail itself is saved to

    ~/.muttdelay/SENDTIMESTAMP.COMPOSETIMESTAMP

The cron job checks if there is any SENDTIMESTAMP lower than the current unix time stamp. And if so, all matching mails are sent.

=head1 LICENSE

See package description or project website.

=head1 AUTHOR

Paul C. Buetow - <http://paul.buetow.org>

=cut
