#!/usr/bin/env bash

# (c) 2014 by Paul C. Buetow

declare -r VERSION='VERSION_DEVEL'
declare -r ARG1="${1}" ; shift
declare -r ARG2="${1}" ; shift
declare -r DEFAULTRC=/etc/default/muttdelay
declare -r NOW=$(date +%s)

usage () {
  cat - <<USAGE >&2
  Usage: $0 mutt|cron
USAGE
}

# Run by a periodic cron job
cron () {

  ls "${QUEUE}" |
  grep -v .body |
  while read mail; do
    when=$(sed -E 's/^([0-9]+)\..*/\1/' <<< "${mail}")
    if [ ${NOW} -gt ${when} ]; then
      fullpath="${QUEUE}/${mail}"
      to=$(formail -xto: < "${fullpath}")
      cc=$(formail -xcc: < "${fullpath}")
      bcc=$(formail -xbcc: < "${fullpath}")
      subject=$(formail -xsubject: < "${fullpath}")

      sed '1,/^$/d' "${fullpath}" > "${fullpath}.body"

      mutt "${to}" -s "${subject}" -c "${cc}" -b "${bcc}" \
        < "${fullpath}.body" && rm "${fullpath}"*
    fi
  done
}

# Run from vim
vim () {
  declare -r mail="${ARG2}"
  declare -i days=0

  echo -n 'In how many days should I send this mail?: '
  read days

  declare -i future=$(( $days * 86400 + $NOW ))
  cp -v "${mail}" "${QUEUE}/${future}.${NOW}"
}

source "${DEFAULTRC}"

[ ! -d "${QUEUE}" ] && mkdir "${QUEUE}" && chmod 0700 "${QUEUE}"

case "${ARG1}" in
  cron) cron;;
  vim)  vim;;
  *)    usage;;
esac

exit 0

# vim: filetype=sh
