#!/usr/bin/env bash

# (c) 2014 by Paul C. Buetow

declare -r VERSION='VERSION_DEVEL'
declare -r ARG="${1}" ; shift
declare -r QUEUE="${HOME}/.maildelayed"
declare -r MAILCMD='msmtp -t'

usage () {
  cat - <<USAGE >&2
  Usage: $0 mutt|cron
USAGE
}

# Run by a periodic cron job
cron () {
  declare -r now=$(date +%s)

  ls "${QUEUE}" |
  while read mail; do
    when=$(sed -E 's/^([0-9]+)\..*/\1/' <<< "${mail}")
    if [ $now -gt $when ]; then
      $MAILCMD < "${QUEUE}/${mail}" && rm "${QUEUE}/${mail}"
    fi
  done
}

# Run from mutt
mutt () {
  echo Not yet implemented
  exit 3
}

[ ! -d "${QUEUE}" ] && mkdir "${QUEUE}" && chmod 0700 "${QUEUE}"

case "${ARG}" in
  cron) cron;;
  mutt) mutt;;
  *)    usage;;
esac

exit 0

# vim: filetype=sh
